# Generated by Django 4.1.7 on 2023-03-04 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='projects_as_developer', to=settings.AUTH_USER_MODEL, verbose_name='devs'),
        ),
    ]
