# Generated by Django 4.1.7 on 2023-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackplatform', '0002_project_customer_alter_project_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
