# Generated by Django 4.1.7 on 2023-03-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackplatform', '0005_order_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='is_published',
        ),
    ]
