# Generated by Django 4.1.7 on 2023-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackplatform', '0006_remove_cv_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
